<%@ Page Title="Privacy Policy — Reyla" Language="C#" MasterPageFile="~/Reyla.Master" AutoEventWireup="true" CodeBehind="Privacy.aspx.cs" Inherits="Reyla.Privacy" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

<div class="row justify-content-center">
    <div class="col-12 col-xl-9">

        <div class="text-center my-4">
            <h3 class="fw-bold">Privacy Policy</h3>
            <p class="text-muted">Effective Date: March 2, 2026 &nbsp;&middot;&nbsp; Last Updated: March 17, 2026</p>
        </div>

        <div class="card">
            <div class="card-body" style="font-size:14px;line-height:1.8;">

                <p class="fst-italic text-muted">This Privacy Policy explains how Reyla ("we," "us," or "our") collects, uses, and protects information when you use our commercial real estate broker platform.</p>

                <h5 class="fw-semibold mt-4">1. Information We Collect</h5>
                <p>We collect the following categories of information:</p>
                <ul>
                    <li><strong>Account information:</strong> Name, email address, organization name, billing information, and other registration details you provide.</li>
                    <li><strong>Usage data:</strong> Pages visited, features used, search queries, prospect records created, and other interactions with the Platform.</li>
                    <li><strong>Property and transaction data:</strong> Property addresses, prospect notes, deal information, and comparable sales data you enter or save within the Platform.</li>
                    <li><strong>Technical data:</strong> IP address, browser type, device information, and log data generated by your use of the Platform.</li>
                </ul>

                <h5 class="fw-semibold mt-4">2. How We Use Your Information</h5>
                <p>We use collected information to:</p>
                <ul>
                    <li>Provide, operate, and improve the Platform and its features.</li>
                    <li>Process billing and manage your subscription.</li>
                    <li>Send transactional communications (account confirmations, receipts, service notices).</li>
                    <li>Respond to support requests and provide customer service.</li>
                    <li>Monitor for security incidents, fraud, and abuse.</li>
                    <li>Comply with legal obligations.</li>
                </ul>
                <p>We do not sell your personal information to third parties.</p>

                <h5 class="fw-semibold mt-4">3. Third-Party Data Providers</h5>
                <p>The Platform incorporates property data sourced from third-party providers, including <strong>CoreLogic Solutions, LLC</strong>. When you use property search, valuation, or data enrichment features, queries are transmitted to CoreLogic's API on your behalf. CoreLogic's handling of data transmitted through its API is governed by its own privacy practices. Further details regarding CoreLogic's privacy approach can be found at <a href="https://www.corelogic.com/ccpa/" target="_blank" rel="noopener">www.corelogic.com/ccpa/</a>.</p>
                <p>Reyla, as the data controller, is responsible for how CoreLogic-sourced data is displayed and stored within the Platform. CoreLogic acts as a service provider processing data on our behalf solely to deliver the services specified in our agreement with them.</p>

                <h5 class="fw-semibold mt-4">4. Data Retention</h5>
                <p>We retain your account and usage data for as long as your account is active and for a reasonable period thereafter to comply with legal obligations, resolve disputes, and enforce our agreements. Property snapshot data retrieved from third-party providers is cached for a maximum of 30 days, after which it must be re-pulled from the source. You may request deletion of your account data by contacting us at <a href="mailto:support@reyla.ai">support@reyla.ai</a>.</p>

                <h5 class="fw-semibold mt-4">5. Data Security</h5>
                <p>We implement industry-standard administrative, technical, and physical safeguards to protect your information from unauthorized access, disclosure, alteration, and destruction. These measures include:</p>
                <ul>
                    <li>TLS encryption for all data in transit.</li>
                    <li>Authentication-gated access to all application features.</li>
                    <li>Rate limiting and session controls to prevent unauthorized data extraction.</li>
                    <li>Restricted access to production systems on a need-to-know basis.</li>
                </ul>
                <p>No method of transmission over the Internet is 100% secure. While we strive to protect your information, we cannot guarantee absolute security.</p>

                <h5 class="fw-semibold mt-4">6. Cookies and Tracking</h5>
                <p>We use session cookies required for authentication and platform functionality. We do not use third-party advertising cookies or behavioral tracking cookies. You may disable cookies in your browser settings, but doing so may affect Platform functionality.</p>

                <h5 class="fw-semibold mt-4">7. Sharing of Information</h5>
                <p>We do not sell or rent your personal information. We may share information with:</p>
                <ul>
                    <li><strong>Service providers</strong> who assist in operating the Platform (e.g., hosting, payment processing), under confidentiality obligations.</li>
                    <li><strong>CoreLogic Solutions, LLC</strong> and other licensed data providers, solely as necessary to fulfill API requests you initiate.</li>
                    <li><strong>Law enforcement or regulators</strong>, when required by applicable law or valid legal process.</li>
                    <li><strong>Successor entities</strong>, in connection with a merger, acquisition, or sale of assets, with notice to affected users.</li>
                </ul>

                <h5 class="fw-semibold mt-4">8. California Privacy Rights (CCPA)</h5>
                <p>If you are a California resident, you may have rights under the California Consumer Privacy Act (CCPA) with respect to personal information we hold about you, including the right to know, the right to delete, and the right to opt out of sale. We do not sell personal information. To exercise your rights, contact us at <a href="mailto:support@reyla.ai">support@reyla.ai</a>. We will respond within 45 days as required by law.</p>
                <p>With respect to personal information processed through CoreLogic's services: CoreLogic's CCPA practices are described at <a href="https://www.corelogic.com/ccpa/" target="_blank" rel="noopener">www.corelogic.com/ccpa/</a>. CoreLogic will cooperate with us to facilitate applicable consumer rights requests.</p>

                <h5 class="fw-semibold mt-4">9. Children's Privacy</h5>
                <p>The Platform is not directed to individuals under the age of 18. We do not knowingly collect personal information from minors. If you believe a minor has provided us information, please contact us so we can delete it.</p>

                <h5 class="fw-semibold mt-4">10. Changes to This Policy</h5>
                <p>We may update this Privacy Policy from time to time. We will notify you of material changes by email or in-app notification before the changes take effect. Your continued use of the Platform after the updated effective date constitutes acceptance.</p>

                <h5 class="fw-semibold mt-4">11. Contact Us</h5>
                <p>For privacy questions or requests, contact us at:<br>
                <a href="mailto:support@reyla.ai">support@reyla.ai</a><br>
                Reyla<br>1023 Jena Street<br>New Orleans, Louisiana 70115</p>

            </div>
        </div>

        <p class="text-center text-muted mt-3 mb-5" style="font-size:12px;">
            <a href="/Terms.aspx" class="text-muted">Terms of Service</a>
            &nbsp;&middot;&nbsp;
            <a href="/Secure/Index" class="text-muted">Back to Dashboard</a>
        </p>

    </div>
</div>

</asp:Content>
