//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.Secure.Prospects
{
    public partial class Comps
    {
        /// <summary>
        /// hdnProspectId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnProspectId;

        /// <summary>
        /// hdnPropertyId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnPropertyId;

        /// <summary>
        /// hdnSubjectClip control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectClip;

        /// <summary>
        /// hdnSubjectLat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectLat;

        /// <summary>
        /// hdnSubjectLng control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectLng;

        /// <summary>
        /// hdnSubjectAddr control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectAddr;

        /// <summary>
        /// hdnSubjectSqFt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectSqFt;

        /// <summary>
        /// hdnSubjectYearBuilt control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectYearBuilt;

        /// <summary>
        /// hdnSubjectSalePrice control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectSalePrice;

        /// <summary>
        /// hdnSubjectSaleDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectSaleDate;

        /// <summary>
        /// hdnSubjectPpsf control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSubjectPpsf;

        /// <summary>
        /// hdnRadiusMiles control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnRadiusMiles;

        /// <summary>
        /// hdnCompsJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnCompsJson;

        /// <summary>
        /// hdnSelectedClips control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnSelectedClips;

        /// <summary>
        /// hdnMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnMessage;

        /// <summary>
        /// hdnMessageType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnMessageType;

        /// <summary>
        /// hdnStreetViewKey control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnStreetViewKey;
    }
}
