//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.Secure.Prospects
{
    public partial class Pipeline
    {
        protected global::System.Web.UI.WebControls.HiddenField hdnBoardJson;
        protected global::System.Web.UI.WebControls.HiddenField hdnProspectsJson;
    }
}
