//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.Secure.Prospects
{
    public partial class PropertyDetail
    {
        protected global::System.Web.UI.WebControls.HiddenField hdnClip;
        protected global::System.Web.UI.WebControls.HiddenField hdnFipsCode;
        protected global::System.Web.UI.WebControls.HiddenField hdnLat;
        protected global::System.Web.UI.WebControls.HiddenField hdnLng;
        protected global::System.Web.UI.WebControls.HiddenField hdnStreetViewKey;
        protected global::System.Web.UI.WebControls.HiddenField hdnDocResult;

        protected global::System.Web.UI.WebControls.Image imgStreetView;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPhotoPlaceholder;
        protected global::System.Web.UI.WebControls.Literal litAddress;
        protected global::System.Web.UI.WebControls.Literal litCityStateZip;
        protected global::System.Web.UI.WebControls.PlaceHolder phSignals;
        protected global::System.Web.UI.WebControls.HyperLink lnkGoogleMaps;
        protected global::System.Web.UI.WebControls.HyperLink lnkBackToComps;
        protected global::System.Web.UI.WebControls.LinkButton btnToggleProspect;
        protected global::System.Web.UI.WebControls.LinkButton btnRemoveProspect;
        protected global::System.Web.UI.WebControls.LinkButton btnRefreshData;

        protected global::System.Web.UI.WebControls.PlaceHolder phProspectCard;
        protected global::System.Web.UI.WebControls.PlaceHolder phDiagnostics;
        protected global::System.Web.UI.WebControls.PlaceHolder phCompMgmt;
        protected global::System.Web.UI.WebControls.HiddenField hdnToggleClip;
        protected global::System.Web.UI.WebControls.HiddenField hdnToggleAction;
        protected global::System.Web.UI.WebControls.HiddenField hdnToggleProspectId;

        // Overview tab
        protected global::System.Web.UI.WebControls.Literal litApn;
        protected global::System.Web.UI.WebControls.Literal litClip;
        protected global::System.Web.UI.WebControls.Literal litPropertyUse;
        protected global::System.Web.UI.WebControls.Literal litZoning;
        protected global::System.Web.UI.WebControls.Literal litLotSize;
        protected global::System.Web.UI.WebControls.Literal litCounty;
        protected global::System.Web.UI.WebControls.Literal litFips;

        protected global::System.Web.UI.WebControls.Literal litBldgSqFt;
        protected global::System.Web.UI.WebControls.Literal litYearBuilt;
        protected global::System.Web.UI.WebControls.Literal litEffYearBuilt;
        protected global::System.Web.UI.WebControls.Literal litStories;
        protected global::System.Web.UI.WebControls.Literal litConstruction;
        protected global::System.Web.UI.WebControls.Literal litRoofType;
        protected global::System.Web.UI.WebControls.Literal litCondition;
        protected global::System.Web.UI.WebControls.Literal litBedrooms;
        protected global::System.Web.UI.WebControls.Literal litBathrooms;
        protected global::System.Web.UI.WebControls.Literal litTotalRooms;

        protected global::System.Web.UI.WebControls.Literal litAvmValue;
        protected global::System.Web.UI.WebControls.Literal litAvmRange;
        protected global::System.Web.UI.WebControls.Literal litAvmConfidence;
        protected global::System.Web.UI.WebControls.Literal litRentEstimate;
        protected global::System.Web.UI.WebControls.Literal litCapRate;
        protected global::System.Web.UI.WebControls.Literal litEquity;
        protected global::System.Web.UI.WebControls.Literal litTaxYear;
        protected global::System.Web.UI.WebControls.Literal litAssessedValue;
        protected global::System.Web.UI.WebControls.Literal litLandValue;
        protected global::System.Web.UI.WebControls.Literal litImprovementValue;
        protected global::System.Web.UI.WebControls.Literal litTaxAmount;
        protected global::System.Web.UI.WebControls.Literal litTaxDelinquent;

        protected global::System.Web.UI.WebControls.Literal litPropensityScore;
        protected global::System.Web.UI.WebControls.Literal litPropensityTier;
        protected global::System.Web.UI.WebControls.Literal litAbsentee;
        protected global::System.Web.UI.WebControls.Literal litInvoluntaryLiens;
        protected global::System.Web.UI.WebControls.Literal litTaxDelinquencySignal;
        protected global::System.Web.UI.WebControls.Literal litPermitSignal;

        protected global::System.Web.UI.WebControls.Panel pnlHoa;
        protected global::System.Web.UI.WebControls.Literal litHoaName;
        protected global::System.Web.UI.WebControls.Literal litHoaFee;
        protected global::System.Web.UI.WebControls.Literal litHoaFrequency;
        protected global::System.Web.UI.WebControls.Literal litHoaPhone;

        protected global::System.Web.UI.WebControls.Literal litFloodRisk;
        protected global::System.Web.UI.WebControls.Literal litFireRisk;
        protected global::System.Web.UI.WebControls.Literal litWindRisk;
        protected global::System.Web.UI.WebControls.Literal litHeatRisk;

        protected global::System.Web.UI.WebControls.PlaceHolder phPermits;
        protected global::System.Web.UI.WebControls.Repeater rptPermits;
        protected global::System.Web.UI.WebControls.Panel pnlNoPermits;

        // Ownership tab
        protected global::System.Web.UI.WebControls.Literal litOwnerName;
        protected global::System.Web.UI.WebControls.Literal litOwner1;
        protected global::System.Web.UI.WebControls.Literal litOwner2;
        protected global::System.Web.UI.WebControls.Literal litOwnershipType;
        protected global::System.Web.UI.WebControls.Literal litAbsenteeOwner;
        protected global::System.Web.UI.WebControls.Literal litMailStreet;
        protected global::System.Web.UI.WebControls.Literal litMailCityStateZip;

        protected global::System.Web.UI.WebControls.PlaceHolder phTransfers;
        protected global::System.Web.UI.WebControls.Repeater rptTransfers;
        protected global::System.Web.UI.WebControls.Panel pnlNoTransfers;

        protected global::System.Web.UI.WebControls.PlaceHolder phMortgages;
        protected global::System.Web.UI.WebControls.Repeater rptMortgages;
        protected global::System.Web.UI.WebControls.Panel pnlNoMortgages;

        protected global::System.Web.UI.WebControls.PlaceHolder phVolLiens;
        protected global::System.Web.UI.WebControls.Repeater rptVolLiens;
        protected global::System.Web.UI.WebControls.Panel pnlNoVolLiens;

        protected global::System.Web.UI.WebControls.PlaceHolder phInvLiens;
        protected global::System.Web.UI.WebControls.Repeater rptInvLiens;
        protected global::System.Web.UI.WebControls.Panel pnlNoInvLiens;

        // Documents tab
        protected global::System.Web.UI.WebControls.Panel pnlDocs;
        protected global::System.Web.UI.WebControls.Repeater rptDocs;
        protected global::System.Web.UI.WebControls.Panel pnlNoDocs;

        protected global::System.Web.UI.WebControls.Panel pnlDocViewer;
        protected global::System.Web.UI.WebControls.Literal litDocTitle;
        protected global::System.Web.UI.WebControls.Panel pnlDocError;
        protected global::System.Web.UI.WebControls.Literal litDocError;
        protected global::System.Web.UI.WebControls.Panel pnlDocPages;
        protected global::System.Web.UI.WebControls.Repeater rptDocPages;

        // ── Owner Contact controls ────────────────────────────────────────
        protected global::System.Web.UI.WebControls.LinkButton   btnEditContact;
        protected global::System.Web.UI.WebControls.LinkButton   btnCancelContact;
        protected global::System.Web.UI.WebControls.LinkButton   btnCancelContact2;
        protected global::System.Web.UI.WebControls.LinkButton   btnSaveContact;
        protected global::System.Web.UI.WebControls.Panel        pnlContactRead;
        protected global::System.Web.UI.WebControls.Panel        pnlContactEdit;
        protected global::System.Web.UI.WebControls.Panel        pnlContactEmpty;
        protected global::System.Web.UI.WebControls.Panel        pnlContactData;
        protected global::System.Web.UI.WebControls.Panel        pnlContactNotes;
        protected global::System.Web.UI.WebControls.Panel        pnlContactSaveAlert;
        protected global::System.Web.UI.WebControls.Literal      litContactSaveAlert;
        protected global::System.Web.UI.WebControls.Literal      litContactName;
        protected global::System.Web.UI.WebControls.Literal      litContactPhone;
        protected global::System.Web.UI.WebControls.Literal      litContactEmail;
        protected global::System.Web.UI.WebControls.Literal      litContactMailing;
        protected global::System.Web.UI.WebControls.Literal      litContactNotes;
        protected global::System.Web.UI.WebControls.Literal      litPreferredContact;
        protected global::System.Web.UI.WebControls.TextBox      txtContactName;
        protected global::System.Web.UI.WebControls.TextBox      txtContactPhone;
        protected global::System.Web.UI.WebControls.TextBox      txtContactEmail;
        protected global::System.Web.UI.WebControls.TextBox      txtContactMailing;
        protected global::System.Web.UI.WebControls.TextBox      txtContactNotes;
        protected global::System.Web.UI.WebControls.DropDownList ddlPreferredContact;
        protected global::System.Web.UI.WebControls.HiddenField  hdnContactSaved;
        protected global::System.Web.UI.WebControls.HiddenField  hdnOwnershipPostback;
        protected global::System.Web.UI.WebControls.HiddenField  hdnNotesProspectId;

        // People tab
        protected global::System.Web.UI.WebControls.HiddenField  hdnPropertyId;
        protected global::System.Web.UI.WebControls.HiddenField  hdnPeopleHandlerUrl;
    }
}
