//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.Secure.Prospects
{
    public partial class ProspectsList
    {
        protected global::System.Web.UI.WebControls.Literal litSubtitle;
        protected global::System.Web.UI.WebControls.Literal litTotalCount;
        protected global::System.Web.UI.WebControls.Literal litNewCount;
        protected global::System.Web.UI.WebControls.Literal litActiveCount;
        protected global::System.Web.UI.WebControls.Literal litClosedCount;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        protected global::System.Web.UI.WebControls.Panel pnlTable;
        protected global::System.Web.UI.WebControls.Repeater rptProspects;
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
