//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.Secure.Prospects
{
    public partial class Search
    {
        /// <summary>
        /// txtStreetAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtStreetAddress;

        /// <summary>
        /// txtCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCity;

        /// <summary>
        /// txtState control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtState;

        /// <summary>
        /// txtZip control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtZip;

        /// <summary>
        /// hdnPropertyId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnPropertyId;

        /// <summary>
        /// hdnStreetViewKey control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnStreetViewKey;

        /// <summary>
        /// hdnClip control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnClip;

        /// <summary>
        /// hdnDetailClip control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnDetailClip;

        /// <summary>
        /// hdnLat control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnLat;

        /// <summary>
        /// hdnLng control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnLng;

        /// <summary>
        /// hdnAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnAddress;

        /// <summary>
        /// hdnResultsJson control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnResultsJson;

        /// <summary>
        /// hdnMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnMessage;

        /// <summary>
        /// hdnMessageType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnMessageType;
    }
}
