// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

namespace Reyla.Secure
{
    public partial class ActivityFeed
    {
        protected global::System.Web.UI.WebControls.Literal          litSubtitle;
        protected global::System.Web.UI.WebControls.Literal          litFeedTitle;
        protected global::System.Web.UI.WebControls.Literal          litCount;
        protected global::System.Web.UI.WebControls.LinkButton        btnScopeMine;
        protected global::System.Web.UI.WebControls.LinkButton        btnScopeOrg;
        protected global::System.Web.UI.WebControls.DropDownList      ddlType;
        protected global::System.Web.UI.WebControls.TextBox           txtDateFrom;
        protected global::System.Web.UI.WebControls.TextBox           txtDateTo;
        protected global::System.Web.UI.WebControls.TextBox           txtSearch;
        protected global::System.Web.UI.WebControls.LinkButton        btnClear;
        protected global::System.Web.UI.WebControls.Panel             pnlEmpty;
        protected global::System.Web.UI.WebControls.Panel             pnlTimeline;
        protected global::System.Web.UI.WebControls.Repeater          rptActivity;
    }
}
