//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.UserControls {

    public partial class MasterPageThemeSettings {

        /// <summary>pnlThemeSettings control — hidden for anonymous users.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlThemeSettings;
    }
}
