//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.UserControls {

    public partial class MasterPageTopbar {

        /// <summary>divSearch — auth-gated search bar.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divSearch;

        /// <summary>divNotif — notification dropdown, authenticated only.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divNotif;

        /// <summary>divSettings — theme settings button, authenticated only.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divSettings;

        /// <summary>divDarkMode — light/dark toggle, authenticated only.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divDarkMode;

        /// <summary>divUserMenu — user dropdown, authenticated only.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divUserMenu;

        /// <summary>divAnonLinks — sign in/register buttons, anonymous only.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAnonLinks;

        /// <summary>litNotifBadge control.</summary>
        protected global::System.Web.UI.WebControls.Literal litNotifBadge;

        /// <summary>litNotifCount control.</summary>
        protected global::System.Web.UI.WebControls.Literal litNotifCount;

        /// <summary>litNotifItems control.</summary>
        protected global::System.Web.UI.WebControls.Literal litNotifItems;

        /// <summary>lnkLogout control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkLogout;
    }
}
