//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.Secure.Contacts
{
    public partial class Contact
    {
        protected global::System.Web.UI.WebControls.HiddenField hdnContactId;
        protected global::System.Web.UI.WebControls.HiddenField hdnHandlerUrl;
        protected global::System.Web.UI.WebControls.HiddenField hdnCanEdit;

        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlMain;

        // Header
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAvatar;
        protected global::System.Web.UI.WebControls.Literal              litInitials;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl  divDisplayName;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl  divCompanyLine;
        protected global::System.Web.UI.WebControls.PlaceHolder          phTypeBadges;
        protected global::System.Web.UI.WebControls.PlaceHolder          phBuyerScore;
        protected global::System.Web.UI.WebControls.Literal              litCreatedDate;
        protected global::System.Web.UI.WebControls.Literal              litUpdatedDate;
        protected global::System.Web.UI.WebControls.Panel                pnlUpdatedDate;

        // Contact info
        protected global::System.Web.UI.WebControls.Literal litPhone;
        protected global::System.Web.UI.WebControls.Literal litMobile;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.Literal litLinkedIn;
        protected global::System.Web.UI.WebControls.Panel   pnlNotes;
        protected global::System.Web.UI.WebControls.Literal litNotes;

        // Types
        protected global::System.Web.UI.WebControls.Panel   pnlNoTypes;
        protected global::System.Web.UI.WebControls.Panel   pnlTypesList;
        protected global::System.Web.UI.WebControls.Literal litTypesList;

        // Properties
        protected global::System.Web.UI.WebControls.Panel    pnlNoProperties;
        protected global::System.Web.UI.WebControls.Panel    pnlPropertiesList;
        protected global::System.Web.UI.WebControls.Repeater rptProperties;

        // Activity
        protected global::System.Web.UI.WebControls.Panel    pnlNoActivity;
        protected global::System.Web.UI.WebControls.Panel    pnlActivityList;
        protected global::System.Web.UI.WebControls.Repeater rptActivity;
    }
}
