//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyla.Secure.Contacts
{
    public partial class Index
    {
        /// <summary>badgeCount control.</summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeCount;

        /// <summary>txtSearch control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>ddlContactType control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlContactType;

        /// <summary>ddlStatus control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;

        /// <summary>hdnContactsJson control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnContactsJson;

        /// <summary>hdnContactTypesJson control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnContactTypesJson;

        /// <summary>hdnCanSeeAll control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnCanSeeAll;
    }
}
